msue129
SiftScience/sift-java pull request #88
Opened 2022-12-04 19:24 UTC by sreejithKExalture

Jira: https://sift.atlassian.net/browse/MSUE-129 

changes:

1.  Upgraded java version to 1.8
2. Set user Agent String to Client to identifiable value
3. Updated okhttp to latest(4.10.0)
4. Added a utility method for webhook validation.

2022-12-05 10:54 UTC, viaskal-sift commented on src/test/java/com/siftscience/BaseAppBrowserSiteBrandFieldSetTest.java
> +        String userAgent = "SiftScience/v205 sift-java/3.7.0";
where is the actual code that sets up this agent with lib version?

2022-12-05 11:22 UTC, sreejithKExalture commented on src/test/java/com/siftscience/BaseAppBrowserSiteBrandFieldSetTest.java
> +        String userAgent = "SiftScience/v205 sift-java/3.7.0";
My bad, I missed to checkin that [file](https://github.com/SiftScience/sift-java/blob/6bb67df46e5d6cd2cc9ef45857d981cad60e7f88/src/main/java/com/siftscience/model/Browser.java) Thanks for pointing it out @viaskal-sift. Have added the missing file to the PR.

2022-12-06 18:00 UTC, mpierotti-sift reviewed
Left a comment about the user agent changes, looks good otherwise.

2022-12-06 18:00 UTC, mpierotti-sift commented on src/main/java/com/siftscience/model/Browser.java
> +    @Expose @SerializedName("$user_agent") private String userAgent = String.format("SiftScience/%s sift-java/%s", API_VERSION, APP_VERSION);
I don't think this change is correct for [MSUE-63: (Java) Set user Agent String to Client to identifiable value](https://sift.atlassian.net/browse/MSUE-63). The SDK user agent should be set in the headers of the the requests that the OkHttpClient is making to Sift, but this implementation seems to be changing the default value for `Browser` json data within the request.

2022-12-08 20:12 UTC, sreejithKExalture commented on src/main/java/com/siftscience/model/Browser.java
> +    @Expose @SerializedName("$user_agent") private String userAgent = String.format("SiftScience/%s sift-java/%s", API_VERSION, APP_VERSION);
Hi @mpierotti-sift  Could you please take a look now? Incorporated changes as suggested.

2022-12-08 20:14 UTC, viaskal-sift commented on src/main/java/com/siftscience/Constants.java
> +    public static final String VERSION = "v205";
this is actually API_VERSION

2022-12-08 20:14 UTC, viaskal-sift commented on src/main/java/com/siftscience/Constants.java
> +    public static final String API_VERSION = "3.7.0";
and this is LIB_VERSION, or just VERSION

2022-12-08 20:25 UTC, sreejithKExalture commented on src/main/java/com/siftscience/Constants.java
> +    public static final String API_VERSION = "3.7.0";
Updated

2022-12-08 20:26 UTC, viaskal-sift commented on src/main/java/com/siftscience/SiftMerchantRequest.java
>  public abstract class SiftMerchantRequest<T extends SiftMerchantResponse> {
Not actually related to this PR but I just paid attention to the fact this class doesn't extend `SiftRequest` and based on the description on the latter it should be a superclass for all Sift API requests since it contains some generic logic. Wdyt @mpierotti-sift ?

2022-12-08 20:41 UTC, sreejithKExalture commented on src/main/java/com/siftscience/SiftMerchantRequest.java
>  public abstract class SiftMerchantRequest<T extends SiftMerchantResponse> {
@viaskal-sift  SiftRequest extends SiftResponse which has a status field which is integer type. This was contradicting with the merchant api spec, where the status refer to merchant status which is a string.  I had raised this concern in in slack when I was doing the development.

2022-12-08 20:42 UTC, sreejithKExalture commented on src/main/java/com/siftscience/SiftMerchantRequest.java
>  public abstract class SiftMerchantRequest<T extends SiftMerchantResponse> {
https://siftscience.slack.com/archives/C01ATASUKGW/p1666352107067959?thread_ts=1666352107.067959&cid=C01ATASUKGW

2022-12-12 17:40 UTC, sbogolii-sift requested changes

2022-12-12 17:40 UTC, sbogolii-sift commented on src/main/java/com/siftscience/SiftMerchantRequest.java
> +        Request.Builder okRequestBuilder = new Request.Builder().addHeader("User-Agent", USER_AGENT_HEADER).url(this.url());
Correct me if I am wrong, but I am not sure if it is correct. I think idea is that when user submits request to service backend, which sends data to sift,  we take user's browser User-Agent and call Sift with it.

So basically it is same as to make get/set userAgent , so backend can set the value before calling Sift backend.

2022-12-12 18:36 UTC, sreejithKExalture commented on src/main/java/com/siftscience/SiftMerchantRequest.java
> +        Request.Builder okRequestBuilder = new Request.Builder().addHeader("User-Agent", USER_AGENT_HEADER).url(this.url());
What I understand is that, we need a header in the http requests originating from SDK's which indicate, from which SDK the requests are from. This will help to segregate calls and get an idea of the number of calls coming from each sdk.  Browser's  generic 'User-agent'  header will not provide this info. 

We have similar implementations in other SDK's : https://github.com/SiftScience/sift-python/commit/aad4be10cb8a1f291147fa41ca0fedb3f4b5781b. 

Does that answer your question ?

2022-12-12 19:51 UTC, sbogolii-sift commented on src/main/java/com/siftscience/SiftMerchantRequest.java
> +        Request.Builder okRequestBuilder = new Request.Builder().addHeader("User-Agent", USER_AGENT_HEADER).url(this.url());
I see, ok, thx for clarification :)

2022-12-12 19:52 UTC, sbogolii-sift approved these changes

2022-12-12 21:21 UTC, mpierotti-sift approved these changes
LGTM

2022-12-22 11:48 UTC, merged