Adding the logic to run the sift-integration-app workflow
SiftScience/sift-java pull request #93
Opened 2023-06-22 07:45 UTC by VinayakGadad

2023-06-28 14:36 UTC, btusakul-sift requested changes

2023-06-28 17:35 UTC, VinayakGadad commented on .circleci/config.yml
> +            unzip -j ../build/distributions/sift-java-3.10.0.zip -d app/libs/
Changed it to dynamically pick the versions from gradle properties.

2023-06-28 17:54 UTC, btusakul-sift requested changes

2023-06-28 20:44 UTC, mpierotti-sift approved these changes
LGTM

2023-06-29 18:50 UTC, VinayakGadad commented on .circleci/config.yml
> +            version=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
When I ran the `./gradlew properties -q` it had only 1 version variable. It makes sense if there are multiple matches. 
I have updated the grep accordingly.

2023-06-29 19:02 UTC, btusakul-sift approved these changes
LGTM

2023-06-29 21:36 UTC, merged